export const LOG_ACTIONS = {
  // Auth
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILED: "AUTH_LOGIN_FAILED",
  AUTH_LOGOUT: "AUTH_LOGOUT",
  AUTH_TOKEN_REFRESHED: "AUTH_TOKEN_REFRESHED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_BRUTE_FORCE: "AUTH_BRUTE_FORCE",

  // Password
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",
  PASSWORD_CHANGED: "PASSWORD_CHANGED",

  // User
  USER_REGISTERED: "USER_REGISTERED",
  USER_EMAIL_VERIFIED: "USER_EMAIL_VERIFIED",
  USER_PROFILE_UPDATED: "USER_PROFILE_UPDATED",
  USER_ADDRESS_ADDED: "USER_ADDRESS_ADDED",
  USER_ADDRESS_UPDATED: "USER_ADDRESS_UPDATED",
  USER_ADDRESS_DELETED: "USER_ADDRESS_DELETED",
  USER_DELETED: "USER_DELETED",
  USER_SUSPENDED: "USER_SUSPENDED",
  USER_REACTIVATED: "USER_REACTIVATED",

  // Order
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_SHIPPED: "ORDER_SHIPPED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_REFUND_REQUESTED: "ORDER_REFUND_REQUESTED",
  ORDER_REFUNDED: "ORDER_REFUNDED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",

  // Payment
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_REFUNDED: "PAYMENT_REFUNDED",
  PAYMENT_CHARGEBACK: "PAYMENT_CHARGEBACK",

  // Product & Inventory
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",
  PRODUCT_PUBLISHED: "PRODUCT_PUBLISHED",
  PRODUCT_UNPUBLISHED: "PRODUCT_UNPUBLISHED",
  INVENTORY_UPDATED: "INVENTORY_UPDATED",
  INVENTORY_LOW_STOCK: "INVENTORY_LOW_STOCK",
  INVENTORY_OUT_OF_STOCK: "INVENTORY_OUT_OF_STOCK",

  // Campaign
  CAMPAIGN_CREATED: "CAMPAIGN_CREATED",
  CAMPAIGN_ACTIVATED: "CAMPAIGN_ACTIVATED",
  CAMPAIGN_DEACTIVATED: "CAMPAIGN_DEACTIVATED",
  CAMPAIGN_DELETED: "CAMPAIGN_DELETED",
  COUPON_USED: "COUPON_USED",
  COUPON_INVALID_ATTEMPT: "COUPON_INVALID_ATTEMPT",

  // Admin
  ADMIN_LOGIN: "ADMIN_LOGIN",
  ADMIN_SETTINGS_CHANGED: "ADMIN_SETTINGS_CHANGED",
  ROLE_ASSIGNED: "ROLE_ASSIGNED",
  ROLE_REVOKED: "ROLE_REVOKED",

  // Security
  SECURITY_SUSPICIOUS_IP: "SECURITY_SUSPICIOUS_IP",
  SECURITY_PERMISSION_DENIED: "SECURITY_PERMISSION_DENIED",
  SECURITY_RATE_LIMIT_HIT: "SECURITY_RATE_LIMIT_HIT",
  SECURITY_ACCOUNT_LOCKED: "SECURITY_ACCOUNT_LOCKED",

  // GDPR
  GDPR_DATA_EXPORT_REQUESTED: "GDPR_DATA_EXPORT_REQUESTED",
  GDPR_DATA_DELETE_REQUESTED: "GDPR_DATA_DELETE_REQUESTED",
  GDPR_CONSENT_GIVEN: "GDPR_CONSENT_GIVEN",
  GDPR_CONSENT_REVOKED: "GDPR_CONSENT_REVOKED",

  // System
  SYSTEM_CRON_STARTED: "SYSTEM_CRON_STARTED",
  SYSTEM_CRON_COMPLETED: "SYSTEM_CRON_COMPLETED",
  SYSTEM_CRON_FAILED: "SYSTEM_CRON_FAILED",
  SYSTEM_ERROR: "SYSTEM_ERROR",
  EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
} as const;

export type LogAction = (typeof LOG_ACTIONS)[keyof typeof LOG_ACTIONS];
